name: seeker
description: For happing fun
version: 0.0.2
homepage: https://github.com/msarifin29/seeker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular.ttf
        - asset: assets/Inter-Black.ttf
        - asset: assets/Inter-Bold.ttf
        - asset: assets/Inter-Light.ttf
        - asset: assets/Inter-Medium.ttf
        - asset: assets/Inter-SemiBold.ttf
        - asset: assets/Inter-Bold.ttf
